name: Create Releases

on:
  release:
    types:
      - created

jobs:
  package:
    uses: ./.github/workflows/pkg-binary.yml
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          # - arm64
        os:
          - linux
          - macos
          - win
        fatcore:
          - false
          # - true
    with:
      arch: ${{ matrix.arch }}
      edge: ${{ github.event.release.prerelease }}
      fatcore: ${{ matrix.fatcore }}
      filename: lando-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}${{ matrix.fatcore == false && '-slim' || '' }}
      node-version: "20"
      os: ${{ matrix.os }}
      version: ${{ github.event.release.tag_name }}

  sign:
    uses: ./.github/workflows/sign-binary.yml
    needs:
      - package
    strategy:
      fail-fast: false
      matrix:
        file:
          # - lando-linux-arm64-${{ github.ref_name }}
          # - lando-macos-arm64-${{ github.ref_name }}
          # - lando-win-arm64-${{ github.ref_name }}

          # - lando-linux-x64-${{ github.ref_name }}
          # - lando-macos-x64-${{ github.ref_name }}
          # - lando-win-x64-${{ github.ref_name }}

          # - lando-linux-arm64-${{ github.ref_name }}-slim
          # - lando-macos-arm64-${{ github.ref_name }}-slim
          # - lando-win-arm64-${{ github.ref_name }}-slim

          - lando-linux-x64-${{ github.ref_name }}-slim
          - lando-macos-x64-${{ github.ref_name }}-slim
          - lando-win-x64-${{ github.ref_name }}-slim
    with:
      download-pattern: packaged-lando-*
      file: ${{ matrix.file }}
    secrets:
      apple-notary-user: ${{ secrets.APPLE_NOTARY_USER }}
      apple-notary-password: ${{ secrets.APPLE_NOTARY_PASSWORD }}
      certificate-data: ${{ contains(matrix.file, 'macos') && secrets.APPLE_CERT_DATA || secrets.KEYLOCKER_CLIENT_CERT }}
      certificate-password: ${{ contains(matrix.file, 'macos') && secrets.APPLE_CERT_PASSWORD || secrets.KEYLOCKER_CLIENT_CERT_PASSWORD }}
      keylocker-api-key: ${{ secrets.KEYLOCKER_API_KEY }}
      keylocker-cert-sha1-hash: ${{ secrets.KEYLOCKER_CERT_SHA1_HASH }}
      keylocker-keypair-alias: ${{ secrets.KEYLOCKER_KEYPAIR_ALIAS }}

  build-release-binary-alias:
    uses: ./.github/workflows/release-binary.yml
    needs:
      - sign
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          #- arm64
        os:
          - linux
          - macos
          - win
        type:
          - -slim
          # -
        # alias: ${{ github.event.release.prerelease == false && fromJson('["edge"]') || fromJson('["stable", "edge"]') }}
        alias:
          - edge

    with:
      source: lando-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}${{ matrix.type }}
      destination: lando-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.alias }}${{ matrix.type }}
      download-pattern: signed-lando-*

  build-release-binary-tag:
    uses: ./.github/workflows/release-binary.yml
    needs:
      - sign
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          #- arm64
        os:
          - linux
          - macos
          - win
        type:
          - -slim
          #-
    with:
      source: lando-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}${{ matrix.type }}
      destination: lando-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}${{ matrix.type }}
      download-pattern: signed-lando-*

  checksum:
    uses: ./.github/workflows/generate-checksums.yml
    needs:
      - build-release-binary-alias
      - build-release-binary-tag
    with:
      download-pattern: release-*
      flatten: true
      show: true
      upload-name: release-checksums-${{ github.sha }}

      # - name: Upload checksums to GitHub Releases
      #   uses: softprops/action-gh-release@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     files: sha256sum.txt
      #     fail_on_unmatched_files: true
